server:
  port: 8080
spring:
  datasource:
#    springbasic——对应了数据库名字
    url: jdbc:mysql://1.116.220.137:3306/springbasic?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
#  实体位置+映射xml位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.njucjz.demo.data